apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonora
spec:
  replicas: 2
  selector:
    matchLabels:
      de-app: sonora
  template:
    metadata:
      labels:
        de-app: sonora
        app: de
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: de-app
                operator: In
                values:
                - sonora
            topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: service-configs
        secret:
          secretName: service-configs
          items:
          - key: sonora.yaml
            path: local.yaml
      containers:
      - name: sonora
        image: harbor.cyverse.org/de/sonora
        resources:
          requests:
            cpu: "100m"
            memory: "1Gi"
          limits:
            cpu: "3000m"
            memory: "3Gi"
        env:
        - name: NODE_CONFIG_DIR
          value: "./config:/etc/iplant/de"
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: service-configs
          mountPath: /etc/iplant/de
          readOnly: true
        ports:
        - name: listen-port
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: sonora
spec:
  selector:
    de-app: sonora
  ports:
  - protocol: TCP
    port: 80
    targetPort: listen-port
